In [1]:
# importing libraries 
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [50]:
# readding dataset
df=pd.read_csv("heart.csv")
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [51]:
# checking data type and any null value present
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
age         303 non-null int64
sex         303 non-null int64
cp          303 non-null int64
trestbps    303 non-null int64
chol        303 non-null int64
fbs         303 non-null int64
restecg     303 non-null int64
thalach     303 non-null int64
exang       303 non-null int64
oldpeak     303 non-null float64
slope       303 non-null int64
ca          303 non-null int64
thal        303 non-null int64
target      303 non-null int64
dtypes: float64(1), int64(13)
memory usage: 33.2 KB


In [4]:
a=df['target'].value_counts()
a

1    165
0    138
Name: target, dtype: int64

In [5]:
# seperating dependend and indipendent variables
y=df['target']
x=df.drop(['target'],axis=1)

In [6]:
#importing the train_test_split to validation set
from sklearn.model_selection import train_test_split

In [7]:
#creating a train and validation set
x_train,x_test,y_train,y_test=train_test_split(x,y, random_state=0,test_size=0.2, stratify=y)

In [8]:
#distribution in traing set
y_train.value_counts()

1    132
0    110
Name: target, dtype: int64

In [9]:
#shape of traing set
x_train.shape,y_train.shape

((242, 13), (242,))

In [10]:
#shape of testing set
x_test.shape,y_test.shape

((61, 13), (61,))

# Applying Decision Tree Classifier

In [11]:
# importing the DecisionTree Classifier
from sklearn.tree import DecisionTreeClassifier

In [12]:
#creating decision tree function
dt_model=DecisionTreeClassifier(random_state=0)


In [13]:
#fitting the model
dt_model.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [14]:
#checking the testing score

dt_model.score(x_test,y_test)

0.7704918032786885

In [17]:
#predicting testing set
p=dt_model.predict(x_test)
print(p)

[1 1 1 0 1 1 1 1 1 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 1 0 1 1 0 1 1 0 0 0 1 1 0
 1 0 0 1 1 1 0 0 1 1 0 1 1 0 1 1 1 1 0 0 0 0 0 0]


In [18]:
# importing the confusion metrics
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,p)


array([[22,  6],
       [ 8, 25]], dtype=int64)

In [20]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,p)

0.7704918032786885

# Applying the Random Forest classifier

In [21]:
# immporting random forest model
from sklearn.ensemble import RandomForestClassifier

# create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)


#Train the model using the training sets y_pred=clf.predict

clf.fit(x_train,y_train)

y_pred=clf.predict(x_test)



In [23]:
#model evaluation
#import scikit-learn metrics module for accurecy calculatiion
from sklearn import metrics

#model accuracy,how often is the classifier correct?

print("Accuracy:",metrics.accuracy_score(y_test,y_pred))

Accuracy: 0.819672131147541


In [30]:
# making confusion matrics
from sklearn.metrics import confusion_matrix,classification_report
cm=confusion_matrix(y_pred,y_test)
cm

array([[21,  5],
       [ 7, 28]], dtype=int64)

# Applying the Navie bayes Algorithm

In [26]:
# fitting classifier to the training set
from sklearn.naive_bayes import GaussianNB

clf=GaussianNB()
clf.fit(x_train,y_train)



GaussianNB(priors=None, var_smoothing=1e-09)

In [28]:
# predicting  the test set resutls

y_pred= clf.predict(x_test)
#y_pred

In [31]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.75      0.81      0.78        26
           1       0.85      0.80      0.82        35

   micro avg       0.80      0.80      0.80        61
   macro avg       0.80      0.80      0.80        61
weighted avg       0.81      0.80      0.80        61



# Applying the SVM classifier

In [33]:
#modeling 

#import svm model
from sklearn.svm import SVC

#create a svm classifier

clf=SVC(kernel='linear')

# training the model using the traing sets
clf.fit(x_train,y_train)

#predict the respose for test dataset

y_pred=clf.predict(x_test)

In [34]:
# model evaluation:

#import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# model accuracy: how often is classifier correct ?
print("Accuracy:",metrics.accuracy_score(y_pred,y_test))

Accuracy: 0.8688524590163934


In [35]:
from sklearn.metrics import confusion_matrix,classification_report
cm=confusion_matrix(y_test,y_pred)
cm

array([[22,  6],
       [ 2, 31]], dtype=int64)

In [36]:
CR=classification_report(y_test,y_pred)
print(CR)

              precision    recall  f1-score   support

           0       0.92      0.79      0.85        28
           1       0.84      0.94      0.89        33

   micro avg       0.87      0.87      0.87        61
   macro avg       0.88      0.86      0.87        61
weighted avg       0.87      0.87      0.87        61



In [42]:
#predicting a new value
clf.predict([[41,0,1,128,205,0,0,152,0,1.4,2,0,2]])

array([1], dtype=int64)

In [43]:
df=pd.DataFrame({'actual':y_test,'predicted':y_pred})
df.head()

actual  predicted
24        1          1
67        1          1
13        1          1
112       1          1
80        1          1

# Conclusion of the problem

 Here output in the form of 1,0
 
 
(ie:1=having disease,0=not having disease)




After applying all algorithms we find the best fitting and more accurecy model is the SVM


